#DATABASE_ADDRESS: localhost
#DATABASE_NAME: ct_file_storage
#DATABASE_USERNAME: postgres
#DATABASE_PASSWORD: 123
#URL: jdbc:mysql://root:mLkEfsWYVPIZzswHQIPVxPHRtkbdiaUD@shinkansen.proxy.rlwy.net:59607/railway
#USERNAME: root
#PASSWORD: mLkEfsWYVPIZzswHQIPVxPHRtkbdiaUD