management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  address: 0.0.0.0
  port: 8888
  servlet:
    context-path: /exam-online-system

spring:
  config:
    import:
      - optional:classpath:application-local.yaml
  application:
    name: exam-online-system
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  mail:
    host: smtp.gmail.com
    port: 587
    username: "${EMAIL:}"
    password: "${EMAIL_PASSWORD:}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
  datasource:
#    url: ${URL:jdbc:mysql://localhost:3306/exam_online_system?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
#    username: ${USERNAME:root}
#    password: ${PASSWORD:123}
    url: "${URL:jdbc:mysql://localhost:3306/exam_online_system?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}"
    username: "${DB_USERNAME:root}"
    password: "${DB_PASSWORD:123}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
              - User.Read
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0


jwt:
  secret: "${JWT_SECRET:}"
  expiration: "${JWT_EXPIRATION:}"

logging:
  level:
    com.azure.spring: DEBUG
    org.springframework.security: DEBUG
    edu.exam_online.exam_online_system: DEBUG
origin: "${ORIGIN:http://localhost:3000}"
email:
  name: "${EMAIL:}"

api:
  key: "${BREVO-KEY:null}"