#DATABASE_ADDRESS: localhost
#DATABASE_NAME: ct_file_storage
#DATABASE_USERNAME: postgres
#DATABASE_PASSWORD: 123
#URL: jdbc:mysql://root:mLkEfsWYVPIZzswHQIPVxPHRtkbdiaUD@shinkansen.proxy.rlwy.net:59607/railway
#USERNAME: root
#PASSWORD: mLkEfsWYVPIZzswHQIPVxPHRtkbdiaUD


#; URL=jdbc:mysql://root:mLkEfsWYVPIZzswHQIPVxPHRtkbdiaUD@shinkansen.proxy.rlwy.net:59607/railway
#; USERNAME=root
#; PASSWORD=mLkEfsWYVPIZzswHQIPVxPHRtkbdiaUD

URL: jdbc:mysql://localhost:3306/exam_online_system?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
DB_USERNAME: root
DB_PASSWORD: 123

EMAIL: hoanghuutuyen06022004@gmail.com
EMAIL_PASSWORD: ctrw zreb qvdy vccx

AZURE_CLIENT_ID: 5e8fd1e6-5c31-4b10-873a-c0cbb2565f02
AZURE_CLIENT_SECRET: t3y8Q~RqbY.QtUlSYVdMz53x6GVHVOU3l5Gq1bXV
AZURE_TENANT_ID: 0aa16d8a-a396-4e21-aa14-2a68a45786bc

JWT_SECRET: 18x30Q0l4Sdr783UnbNl6drrmqSobLJB
JWT_EXPIRATION: 86400000

ORIGIN: http://localhost:3000